version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: netpulse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: netpulse123
      MYSQL_DATABASE: netpulse
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: netpulse-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data: